config/routes.rb
KickIt::Application.routes.draw do
  resources :activities
  resources :bucket_lists
  resources :adventures
  
  devise_for :users

  resources :users, only: [:show, :index] do
    resources :bucket_lists
  end
  
  resources :bucket_lists do
    resources :adventures
  end

  root  'pages#index'

  

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  mount_uploader :picture, PictureUploader
  
  state_machine :state, :initial => :incomplete do
    event :complete do
      transition :incomplete => :completed
    end
  end

  validates_presence_of :bucket_list
  validates_presence_of :adventure_description

  belongs_to :user, inverse_of: :adventures
  belongs_to :bucket_list, inverse_of: :adventures
end

app/models/bucket_list.rb
class BucketList < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  validates_presence_of :title
  validates_presence_of :user
  
  has_many :adventures, inverse_of: :bucket_list, dependent: :destroy
  belongs_to :user, inverse_of: :bucket_lists

  def complete?
    adventures.where(state: 'incomplete').count == 0 && adventures.count != 0
  end

  def self.completed
    result = []
    BucketList.all.each do |list|
      if list.complete?
        result << list
      end
    end
    result
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_presence_of :picture
  
  has_many :bucket_lists, inverse_of: :user, dependent: :destroy
  has_many :adventures, inverse_of: :user, dependent: :destroy

  mount_uploader :picture, PictureUploader

  def completed_lists
    @completed_bucket_lists = []
      
    bucket_lists.each do |list|
      if list.complete?
        @completed_bucket_lists << list
      end
    end
    @completed_bucket_lists
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc")
  end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  def new
    @adventure = Adventure.new
    @bucket = BucketList.find(params[:bucket_list_id])
  end

  def create
    @adventure = Adventure.new(adventure_params)
    @adventure.user_id = current_user.id
    @bucket = BucketList.find(params[:bucket_list_id])
    @adventure.bucket_list_id = @bucket.id

    if @adventure.save
      flash[:notice] = 'Your new adventure has been added to this list'
      redirect_to bucket_list_path(@bucket)
    else
      render :new
    end
  end

  def update
    @adventure = Adventure.find(params[:id])

    if @adventure.update_attributes!( adventure_params )
      if @adventure.picture
        @adventure.complete
      end
      redirect_to bucket_list_path(@adventure.bucket_list), notice: 'Photo Updated'
    else
      flash[:alert] = 'Please provide a photo'
      render :show
    end
  end

  def index
    @all_adventures = Adventure.all
    if params[:bucket_list_id]
      @bucket_list = BucketList.find( params[:bucket_list_id] )
      @adventures = Adventure.where( bucket_list_id: @bucket_list.id )
    else
      @bucket_list = nil
      @adventure = Adventure.all
    end
  end

  protected
  def adventure_params
    params.require(:adventure).permit(
      :adventure_description,
      :picture
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :picture]
  end


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/bucket_lists_controller.rb
class BucketListsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :destroy]
  
  def new
    @bucket_list = BucketList.new
  end

  def index
    if current_user
      @user = current_user
      @bucket_lists = current_user.bucket_lists
      @completed_bucket_lists = @user.completed_lists

    else
      @bucket_lists = BucketList.all
      @completed_bucket_lists = BucketList.completed
    end
  end

  def create
    @bucket_list = BucketList.new(reg_params)
    @bucket_list.user = current_user
    if @bucket_list.save
      flash[:notice] = "Your bucket list is created! Add some list items!"
      redirect_to '/bucket_lists'
    else
      render 'new'
    end
  end

  def show
    @bucket_list = BucketList.find(params[:id])
  end

  def destroy
    if current_user
      @user = current_user
      @bucket_list = BucketList.find(params[:id])
      @bucket_list.destroy
      redirect_to "/users/#{@user.id}/bucket_lists/"
    end
  end 

  protected

  def reg_params
    params.require(:bucket_list).permit(
      :title
      )
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.search(params[:q])
    @users = @search.result
  end

  def show
     @user = User.find(params[:id])
     @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: @user.id)
  end

  def user_params
    params.require(:user).permit(:picture, :username)
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<%= render_activities(@activities) %>

app/views/adventures/index.html.erb
<% @all_adventures.each do |adventure| %>
    <div class="adventure-box">
      <div class="adventure-box-inner">
        <p class="adventure-text"><%= adventure.adventure_description %></p>
        
        <% if adventure.state == "incomplete" %>
          <%= simple_form_for [@bucket_list, adventure],
            html: { class: "adventure-box-form" } do |f| %>
          <% end %>
        <% else %>
          <div class="adventipic">
            <%= image_tag(adventure.picture.url) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/adventures/new.html.erb
<%= form_for([@bucket, @adventure]) do |f| %>
   <% if @adventure.errors.any? %>
    
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  
  <% end %>

    <div>
      <%= f.label :adventure_description %>
      <%= f.text_field :adventure_description %>
    </div>

    <div>
      <%= f.submit 'Create a new item!' %>
      <%= link_to 'Cancel', user_bucket_lists_path(@bucket.user) %>
    </div>

<% end %>

app/views/bucket_lists/index.html.erb
<div class="unfinished"><h1>Unfinished Business</h1>
  <table>
    <thead>
      <tr>
        <th>List Title</th>
      </tr>
    </thead>

    <tbody>
        <% @bucket_lists.each do |list| %>
        <% if list.complete? == false %>
          <tr>
            <td class="list-item"><%= link_to "#{list.title}", list %></td> 
            <!-- this is thw show action -->
            <td><%= link_to 'Edit', edit_bucket_list_path(list) %></td>
            <td><%= link_to ' x ', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Create A New List', new_bucket_list_path %>
<div>

<% if @completed_bucket_lists.count != 0 %>

<div class="finished">
  <h1>Completed</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>

      <tbody>
        <% @completed_bucket_lists.each do |list| %>
          <tr>
            <td class="list-item"><%= list.title %></td>
            <td><%= link_to 'Show', list %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/bucket_lists/new.html.erb
<%= form_for @bucket_list do |f| %>
  <% if @bucket_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bucket_list.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @bucket_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>


  <%= f.submit 'Save List!' %>

<%- end -%>

app/views/bucket_lists/show.html.erb
<% if @bucket_list %>
  <p>
    <strong><%=link_to 'Bucket List Your Viewing:', bucket_lists_path %></strong>
    <%= @bucket_list.title %>
  </p>

  <% @bucket_list.adventures.each do |adventure| %>
    <div class="adventure-box">
      <div class="adventure-box-inner">
        <p class="adventure-text">
          <%= adventure.adventure_description %>
        </p>
        
        <% if adventure.state == "incomplete" %>
          <%= simple_form_for [@bucket_list, adventure],
            html: { class: "adventure-box-form" } do |f| %>
            
            <%= f.file_field :picture %>
            <%= f.submit 'Finish adventure!' %>
          <% end %>
        <% else %>
        <div class="adventipic">
         <%= image_tag(adventure.picture.url) %>
        </div>
      <% end %> 
      </div> 
    </div>
  <% end %>

  <% unless @bucket_list.complete? %>
    <%= link_to 'Add item', new_bucket_list_adventure_path(@bucket_list) %>
  <% end %>
<% end %>


 <script>
//   function handleFileSelect(evt) {
//     var files = evt.target.files; // FileList object

//     // Loop through the FileList and render image files as thumbnails.
//     for (var i = 0, f; f = files[i]; i++) {

//       // Only process image files.
//       if (!f.type.match('image.*')) {
//         continue;
//       }

//       var reader = new FileReader();

//       // Closure to capture the file information.
//       reader.onload = (function(theFile) {
//         return function(e) {
//             $('#image_preview').append('<img src="' + e.target.result + '" class="thumbnail"/>')

//         };
//       })(f);

//       // Read in the image file as a data URL.
//       reader.readAsDataURL(f);
//     }
//   }

//   document.getElementById('adventure_picture').addEventListener('change', handleFileSelect, false);
// </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KickIt</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
        </button> -->
        <%= link_to "KickIt", root_path, class: 'navbar-brand' %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><a>Logged in as <strong><%= current_user.username %></strong></a></li>
            <li><%= link_to 'Browse Adventures', adventures_path %></li>
            <li><%= link_to 'Profile', current_user %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>

          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>

   


    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/pages/index.html.erb
<div class="browse-advent-link">
  <button type="button" class="browse btn btn-primary btn-lg"><%= link_to 'Browse Adventures', adventures_path %></button> 
</div>

<h1> What do you want to do before you... </h1>

  <div class="row-fluid">
    <div class="span9">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
      
        <div class="carousel-inner">
          <div class="item active">
            <div class="new_html_code"><h2>turn 40?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>die?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>fly home from Maui?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>get married?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>move out of Boston?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>have your next birthday?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>hit the hay tonight?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>have children?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>watch the clock strike midnight?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>start school?</h2></div>
          </div>

          <div class="item">
            <div class="new_html_code"><h2>see your ex?</h2></div>
          </div>
        </div>



      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
      </div>
    </div>
  </div>

app/views/public_activity/adventure/_create.html.erb
I created an adventure

app/views/public_activity/adventure/_update.html.erb
<% adventure = Adventure.find(activity.trackable_id) %>
<p>
<%= link_to "#{adventure.user.username}", user_path(adventure.user_id) %>
<% if adventure.state = 'completed' %>
  <%= link_to "just completed #{adventure.adventure_description}", bucket_list_path(adventure.bucket_list_id) %>
<% else %>
  <%= link_to "updated #{adventure.adventure_description}", bucket_list_path(adventure.bucket_list_id) %>
<% end %>
</p>

app/views/public_activity/bucket_list/_create.html.erb
<p>
<% bucket_list = BucketList.find(activity.trackable_id) %>

<%= "This bucketlist was created by #{bucket_list.user.username}" %>
<%= link_to "See this bucket_list", bucket_list_path(bucket_list) %>
</p>

app/views/public_activity/bucket_list/_update.html.erb
I updated a bucket list

app/views/users/index.html.erb
<h1>All Da Users</h1>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :username_cont %>
    <%= f.text_field :username_cont %>
  </div>

  <div class="actions">
    <%= f.submit 'Search' %>
  </div>
<% end %>

<% if @users.count == 0 %>
  <p>That user does not exist!</p>
<% end %>

<table id="users">
<% @users.each do |user| %>
  <tr>
    <td><%= link_to(user.username, user) %></td>
    <td><%= image_tag user.picture.url %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p> Welcome to your profile page, homie</p>

<div class="prof-pic">
  <%= image_tag @user.picture.url %>
</div>

<% if @user == current_user %>
  <button type="button" class="btn btn-default btn-lg"><%= link_to "My Bucket Lists!", user_bucket_lists_path(@user) %></button>
  <button type="button" class="btn btn-default btn-lg"><%= link_to "New Bucket List", new_bucket_list_path %></button>
  <button type="button" class="btn btn-default btn-lg"><%= link_to "Browse all Users", users_path %></button>

<% end %>


<%= render_activities(@activities) %>